use std::cell::{Cell, RefCell};
use std::sync::Arc;

use leptos::prelude::*;

use crate::{ArcOneCallback, TabItem};

/// Tab metadata passed to generated tab command text callbacks.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TabCommandContext {
    /// Zero-based index of the tab within its own [`TabList`](crate::TabList).
    ///
    /// This is structural metadata, not user-facing text. It is only shown if
    /// the host application includes it in a generated label.
    pub local_index: usize,
    /// The tab entry being converted into command palette entries.
    ///
    /// `tab.value` is the internal selection value. `tab.label` is the
    /// user-facing label shown by the tab trigger.
    pub tab: TabItem,
}

/// User-facing text and shortcut policy for tab commands generated by
/// [`CommandPalette`](super::CommandPalette).
#[derive(Clone)]
pub struct TabCommandPaletteConfig {
    /// User-facing group name used for generated tab commands.
    ///
    /// Rendered as the command palette section title, for example
    /// `"Navigation"`. The host application should provide this in the active
    /// UI language.
    pub group: String,
    /// User-facing name of the aggregate tab selection command.
    ///
    /// This command uses [`select_shortcut`](Self::select_shortcut) and opens a
    /// parameter prompt with every command-enabled tab.
    pub select_name: String,
    /// Optional user-facing secondary text for the aggregate tab selection
    /// command.
    ///
    /// Rendered below [`select_name`](Self::select_name) when present.
    pub select_description: Option<String>,
    /// User-facing placeholder shown while choosing a tab in the aggregate tab
    /// selection command.
    ///
    /// Example: `"Choose tab"`. The host application should provide this in
    /// the active UI language.
    pub select_placeholder: String,
    /// User-facing shortcut hint and searchable shortcut for the aggregate tab
    /// selection command.
    ///
    /// Example: `"TS"`. Whitespace is ignored and matching is
    /// case-insensitive.
    pub select_shortcut: String,
    /// Builds the user-facing command name for one direct tab command.
    ///
    /// Called for every enabled registered tab whenever the command palette
    /// rebuilds generated tab commands.
    pub tab_name: Arc<dyn Fn(TabCommandContext) -> String + Send + Sync>,
    /// Optionally builds user-facing secondary text for one direct tab command.
    ///
    /// Rendered below the generated direct tab command name when present.
    pub tab_description: Option<Arc<dyn Fn(TabCommandContext) -> Option<String> + Send + Sync>>,
    /// Builds the user-facing option label for a tab inside the aggregate tab
    /// selection command.
    ///
    /// Called for every enabled registered tab. The returned text is shown in
    /// the option list opened by [`select_name`](Self::select_name).
    pub tab_option_label: Arc<dyn Fn(TabCommandContext) -> String + Send + Sync>,
    /// Builds the user-facing shortcut for one direct tab command.
    ///
    /// Receives a zero-based global index across all enabled registered tabs in
    /// registration order. The default produces `"T1"`, `"T2"`, `"T3"`, and so
    /// on.
    pub tab_shortcut: Arc<dyn Fn(usize, TabCommandContext) -> String + Send + Sync>,
}

impl Default for TabCommandPaletteConfig {
    fn default() -> Self {
        Self::new()
    }
}

impl TabCommandPaletteConfig {
    /// Creates tab command text with English defaults.
    ///
    /// Host applications with runtime language switching can pass a derived
    /// config to [`CommandPalette`](super::CommandPalette) and rebuild these
    /// values whenever the active language changes.
    pub fn new() -> Self {
        Self {
            group: String::from("Navigation"),
            select_name: String::from("Select tab"),
            select_description: None,
            select_placeholder: String::from("Choose tab"),
            select_shortcut: String::from("TS"),
            tab_name: Arc::new(|context| format!("Open {}", context.tab.label)),
            tab_description: None,
            tab_option_label: Arc::new(|context| context.tab.label),
            tab_shortcut: Arc::new(|index, _context| format!("T{}", index + 1)),
        }
    }

    /// Sets the user-facing group name used for generated tab commands.
    pub fn group(mut self, group: impl Into<String>) -> Self {
        self.group = group.into();
        self
    }

    /// Sets the user-facing name of the aggregate tab selection command.
    pub fn select_name(mut self, name: impl Into<String>) -> Self {
        self.select_name = name.into();
        self
    }

    /// Sets the optional user-facing description of the aggregate tab selection
    /// command.
    pub fn select_description(mut self, description: impl Into<String>) -> Self {
        self.select_description = Some(description.into());
        self
    }

    /// Sets the user-facing placeholder shown by the aggregate tab selection
    /// prompt.
    pub fn select_placeholder(mut self, placeholder: impl Into<String>) -> Self {
        self.select_placeholder = placeholder.into();
        self
    }

    /// Sets the user-facing shortcut for the aggregate tab selection command.
    pub fn select_shortcut(mut self, shortcut: impl Into<String>) -> Self {
        self.select_shortcut = shortcut.into();
        self
    }

    /// Sets the user-facing command name builder for direct tab commands.
    pub fn tab_name(
        mut self,
        tab_name: impl Fn(TabCommandContext) -> String + Send + Sync + 'static,
    ) -> Self {
        self.tab_name = Arc::new(tab_name);
        self
    }

    /// Sets the user-facing description builder for direct tab commands.
    pub fn tab_description(
        mut self,
        tab_description: impl Fn(TabCommandContext) -> Option<String> + Send + Sync + 'static,
    ) -> Self {
        self.tab_description = Some(Arc::new(tab_description));
        self
    }

    /// Sets the user-facing option label builder used by the aggregate tab
    /// selection command.
    pub fn tab_option_label(
        mut self,
        tab_option_label: impl Fn(TabCommandContext) -> String + Send + Sync + 'static,
    ) -> Self {
        self.tab_option_label = Arc::new(tab_option_label);
        self
    }

    /// Sets the user-facing shortcut builder for direct tab commands.
    pub fn tab_shortcut(
        mut self,
        tab_shortcut: impl Fn(usize, TabCommandContext) -> String + Send + Sync + 'static,
    ) -> Self {
        self.tab_shortcut = Arc::new(tab_shortcut);
        self
    }
}

#[derive(Clone)]
pub(crate) struct RegisteredTabList {
    pub id: usize,
    pub tabs: RwSignal<Vec<TabItem>>,
    pub on_select: ArcOneCallback<String>,
}

thread_local! {
    static NEXT_TAB_REGISTRATION_ID: Cell<usize> = const { Cell::new(1) };
    static NEXT_TAB_LISTENER_ID: Cell<usize> = const { Cell::new(1) };
    static REGISTERED_TAB_LISTS: RefCell<Vec<RegisteredTabList>> = const { RefCell::new(Vec::new()) };
    static TAB_COMMAND_LISTENERS: RefCell<Vec<(usize, RwSignal<u64>)>> = const { RefCell::new(Vec::new()) };
}

pub(crate) fn register_tab_list(
    tabs: RwSignal<Vec<TabItem>>,
    on_select: ArcOneCallback<String>,
) -> usize {
    let id = NEXT_TAB_REGISTRATION_ID.with(|next| {
        let id = next.get();
        next.set(id + 1);
        id
    });

    REGISTERED_TAB_LISTS.with(|registered| {
        registered.borrow_mut().push(RegisteredTabList {
            id,
            tabs,
            on_select,
        });
    });
    notify_tab_command_registry();
    id
}

pub(crate) fn unregister_tab_list(id: usize) {
    REGISTERED_TAB_LISTS.with(|registered| {
        registered.borrow_mut().retain(|entry| entry.id != id);
    });
    notify_tab_command_registry();
}

pub(crate) fn registered_tab_lists() -> Vec<RegisteredTabList> {
    REGISTERED_TAB_LISTS.with(|registered| registered.borrow().clone())
}

pub(crate) fn notify_tab_command_registry() {
    TAB_COMMAND_LISTENERS.with(|listeners| {
        for (_, listener) in listeners.borrow().iter() {
            listener.update(|version| *version += 1);
        }
    });
}

pub(crate) fn register_tab_command_listener(listener: RwSignal<u64>) -> usize {
    let id = NEXT_TAB_LISTENER_ID.with(|next| {
        let id = next.get();
        next.set(id + 1);
        id
    });

    TAB_COMMAND_LISTENERS.with(|listeners| {
        listeners.borrow_mut().push((id, listener));
    });
    id
}

pub(crate) fn unregister_tab_command_listener(id: usize) {
    TAB_COMMAND_LISTENERS.with(|listeners| {
        listeners
            .borrow_mut()
            .retain(|(listener_id, _)| *listener_id != id);
    });
}
