mod button_page;
mod card_page;
mod checkbox_page;
mod color_page;
mod font_page;
mod icon_page;
mod input_page;
mod label_page;
mod select_page;
mod slider_page;
mod tabs_page;
mod tag_page;
mod textarea_page;

pub use button_page::ButtonPage;
pub use card_page::CardPage;
pub use checkbox_page::CheckboxPage;
pub use color_page::ColorPage;
pub use font_page::FontPage;
pub use icon_page::IconPage;
pub use input_page::InputPage;
pub use label_page::LabelPage;
pub use select_page::SelectPage;
pub use slider_page::SliderPage;
pub use tabs_page::TabsPage;
pub use tag_page::TagPage;
pub use textarea_page::TextareaPage;
